FROM registry.fedoraproject.org/fedora:38
ENV TZ=Europe/Madrid

LABEL org.opencontainers.image.source=https://github.com/freeipa/ipa-tuura
LABEL org.opencontainers.image.description="IPA-tuura Container"

# Install dependencies
RUN dnf -y update && dnf -y install \
    dbus-daemon \
    dbus-devel \
    gcc \
    glib2-devel \
    glibc \
    httpd \
    krb5-devel \
    maven \
    mod_ssl \
    mod_wsgi \
    openldap-devel \
    openssl \
    python3-devel \
    python3-netifaces \
    python3-pip \
    python3-sssdconfig \
    python-devel \
    python-ipalib \
    sssd-dbus \
    unzip \
    && dnf clean all

COPY . ipa-tuura
WORKDIR /ipa-tuura
RUN pip install -r src/install/requirements.txt

# Install Unit Test Dependencies
RUN pip install factory_boy coverage==3.6

# Run the unit tests for the integration domains app
RUN python3 src/ipa-tuura/manage.py test domains

RUN coverage run src/ipa-tuura/manage.py test domains -v 2

RUN coverage run manage.py test domains -v 2 && coverage report && coverage html

