version: "3"
services:
  tuura-server:
    container_name: tuura-server
    build:
      context: ../..
      dockerfile: src/prod/Containerfile
    environment:
      - DJANGO_SECRET_KEY="^$z^y$^ndlem@_f1)($_5vye6t!dk#8+8&9=y5*=-r(v465xg+"
      - DJANGO_DEBUG='False'
    ports:
      - 8005:80
      - 3501:3500
      - 4701:81
      - 4430:443
