---
name: Unit tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
	  python3 -m pip install --upgrade pip
          pip instll -r src/install/requirements.txt
      - name: Lint with Flake8
          run: |
          flake8 .
      - name: Run Tests
        run: |
          python src/ipa-tuura/manage.py test
