---
name: Unit tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          podman pull fedora:38

      - name: Get source
        uses: actions/checkout@v3
        with:
          path: 'ipa-tuura'

      - name: Create container and run tests
        run: |
          {
              echo 'FROM fedora:38'
              echo '# set TZ to ensure the test using timestamp'
              echo 'ENV TZ=Europe/Madrid'
              echo 'RUN dnf -y update'
              echo 'RUN dnf -y install python3-sssdconfig maven unzip python3-pip git python3-netifaces python3-devel krb5-devel gcc sssd-dbus dbus-devel glibc glib2-devel dbus-daemon python-devel openldap-devel python-ipalib'
              echo 'RUN dnf clean all'
              echo 'COPY ipa-tuura ipa-tuura'
              echo 'WORKDIR /ipa-tuura'
              echo 'RUN pip install -r src/install/requirements.txt'
              echo 'RUN pip install flake8 dbus-python python-ldap'
              echo 'RUN flake8 . --ignore E265,E123 --exclude ./src/ipa-tuura/root/settings.py,./src/ipa-tuura/ipatuura/migrations/0001_initial.py,./ipatuura-env/*,./src/ipa-tuura/domains/migrations/0001_initial.py'
              echo 'RUN python3 src/ipa-tuura/manage.py test'
          } > podmanfile
          podman build --tag gatingtest -f ./podmanfile
